apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-pipelines-cert
  namespace: envoy-gateway-system
spec:
  secretName: grafana-tls
  dnsNames:
  - aziz-soudani-grafana.eks.karimarous.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod